### PR TITLE
connected Persistence, added run to build.xml

### PR DESCRIPTION
**Pull request by programming2web**
Added run, jar targets to build.xml
Connected Persistence classes to gui
Improved the tests

I probably won't have much time to work on it next week besides probably Wednesday and Thursday, so I guess it's very close to the final version of GUI. 

Please let me know when you have a chance whether it's Ok to merge it.

### CODE REVIEW

**Comment by JeffBlodgett** [comment]
Hi Olga,

If it compiles and runs without error then I'd say merge now.  I'll finally 
have a chance to look at everything tomorrow and would rather be looking at 
the total sum in Master.
- Jeff

**Comment by dbendig** [comment]
Hi Olga,

I tested this on my machine and everything compiles nicely. I tried out the run target and it looks great. I was able to copy and compare directories and output the diff report. Please merge this pull.

Thanks
Dan

**Comment by programming2web** [comment]
Thank you, guys! 
Merging.

**Comment by JeffBlodgett** [comment]
At long last (away from a computer last week) I’ve been able to get back into the project this morning.  I’m correcting things I’ve noticed in the operation of the BusinessLogic package (no changes to the public API – won’t affect other parts of the project).

A couple GUI comments:
- Very nice!  Speaking GUI wise, suggested future changes (were we to continue development past the confines of the course timeline) would be to enable the selection of specific files (in addition to folders) and selection of files/folders outside of the user’s home directory.
- When copying files, could you have the control that lists and updates the individual file copies position the most recent copy at the top of the list, rather than the bottom?  If not, could you enable automatically scrolling to the bottom as new items are added?  It's difficult to see the incrementing of the percentage of each file as it is being copied (have to continually scroll to the bottom of the list manually.
- On that same Copying files to… screen, I suggest changing each item’s “Copying …” text to “Creating …” since the pathname specified is that of the copy that is being created in the target.
- Remove the “File Sieve” label at the top of the forms.  It looks redundant when the program title is displayed by default by the JVM in the window’s title bar.
- Jeff

**Comment by JeffBlodgett** [comment]
FYI – the “FileTreeModelTest” class’ “testContruction()” test is failing atop Windows platforms because the test’s first line assumes a file path sepator of “/”, which is only valid for Linux-based platforms.  Change the line to the following and it passes (use “File.separator”):

String root = testTreeModel.getRoot().toString() + File.separator;

**Comment by programming2web** [comment]
Jeff, thanks a lot! Right, I didn't test it on Windows. I'll look through all my files for File separator tonight and will fix it - there are probably more instances of it than just in FileTreeModelTest.

Your comments are very valuable. Thank you for looking into this and for the suggestions.

I'll work on the copy screen and displaying the files being copied on Wednesday - Thursday. It's a good point. Will also change "copying" to "creating".

Ok, I'll remove the "FileSieve" label from all screens. That should be easy.

Thank you, Jeff!

**Pull request merged**
