### PR TITLE
Persistence

### PR DESCRIPTION
**Pull request by dbendig**
This pull includes the completion of the user preferences classes with changes so that the window is now set appropriately inside of the screen, a default action of centering the window on screen, and support for multiple reference paths provided by the user. This also includes a simple implementation of the DiffReport with an HTML output defined. The HTML output needs to be more thoroughly implemented with styling, and the test for it could be more mature as well.

### CODE REVIEW

**Comment by dbendig** [comment]
I should note that I included the jsoup library for working with HTML. Apparently that didn't commit properly but I committed the file separately and it should be working now.

**Comment by programming2web** [comment]
Dan, looks good. I'll connect the window placement to gui. No objections to merge.
Looks like we'll need another screen to display the report. I hope I'll have time to do it. If not - then we could just save the report (that's how I initially understood it) and users will be able to open it with their browsers.

**Comment by dbendig** [comment]
Hi Olga, You interpreted it correctly, but for now I'm returning the report as a string. If nothing else that makes it easier for testing purposes, but I figured it makes sense for the class itself (if maybe not for our explicit use.) I can change that aspect of it if need be.

**Comment by dbendig** [comment]
After some testing and a go-ahead from Jeff, I'm merging this pull request.

**Pull request merged**
