### PR TITLE
Report update

### PR DESCRIPTION
**Pull request by dbendig**
This pull includes latest GUI and Persistence changes. The report now includes deletion information in the report output and should work on any platform. I also made a small change in response to the professor's comments.

### CODE REVIEW

**Comment by programming2web** [comment]
Looks good. No objections to merge.

**Comment by JeffBlodgett** [comment]
Yes, let's merge so I can test and view atop Windows platform. Getting confused now... I'd like to test the total project sum with all of Olga's changes to date plus your own, even if Olga may be doing additional work this weekend (project needs to be ready for professor's review by some point on Sunday).

**Comment by JeffBlodgett** [comment]
Testing now...

**Comment by JeffBlodgett** [comment]
All tests well. This is really cool stuff folks! Please go ahead and merge this pull.
At this point, the only changes I'm making are documentation-related and what changes I make will be complete by the end of the day. Are either of you planning to commit any more work, or are we about ready to signal to the professor that our project is ready for turn-in?

**Comment by dbendig** [comment]
I think this is a good stopping point, Jeff. Let's turn it in.

**Comment by JeffBlodgett** [comment]
Ok... let me work further on documenting (JavaDoc'in) the BusinessLogic today.  Then we can be finished, unless Olga has any further commits/merges to make herself.

**Comment by JeffBlodgett** [comment]
Just noticed that while non of the tests are failed and the build is reported as successful, there is an odd JUnit message about an "Exception while removing reference" between the CopyJobListenerTest and FileTreeModelTest.  Either of those tests can be run from IDEA individually without any mention of a problem so I'm not sure what to make of it. Do we ignore it and chalk-it-up to a problem/bug in the JUnit framework itself?

[junit] Running FileSieve.gui.CopyJobListenerTest
[junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.706 sec
[junit] Exception while removing reference.
[junit] Running FileSieve.gui.FileTreeModelTest
[junit] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.095 sec

**Comment by dbendig** [comment]
Some quick searching returns this: 
http://stackoverflow.com/questions/2873449/occasional-interruptedexception-when-quitting-a-swing-application

Looking at the code I notice there's no cleanup, so maybe if we add a cleanup method that cleanly disposes of the copyscreen and controller that error will go away. If you want I can try it out tonight.

**Comment by JeffBlodgett** [comment]
OMG – that’s funny.  I remember that same page leading me to a solution to fix the same issue in a program I was writing for the office – it just took your link to remind me.  It may or may not be related, but the issue with my office app seemed to be a bug in Oracle’s JFileChooser.  Going through the code for that office app, I fail to find the exact solution but if memory serves me correctly it was related to the form needing to be disposed(), though I suspect it was my handling of some other cleanup tasks that delayed closing of the form just long enough to permit my JFileChooser to stop causing an exception upon form disposal.  Unfortunately my efforts to quickly “dispose” of this exception have failed (I remember it being a real pain in the neck before too).  I did notice that we are using System.exit(0) to terminate the GUI.  That is generally considered bad practice since any ongoing background threads are immediately terminated.  In fact, we should probably be ensuring that an active copy job has been cancelled and the copy job completed (if either of you do this, do not use the copy jobs “awaitCompletion()” method from the EDT else you’ll wind up in an indefinite hang… probably best to use its “isRunning()” method and to look for an “UpdateCopyJobProgress” method call with a job progress of 100% in the SwingCopyJobListener).  Indeed, I just checked and that System.exit(0) leaves the last file that has been copied in an incomplete state.

I’m running out of time fast so I’m getting back to the JavaDocs now.
- Jeff

**Comment by programming2web** [comment]
Thanks, guys. I did want to address some of Spencer's comments but couldn't get to it on Thursday as planned and it looks like I won't have any time this weekend either. So I'd call it final. 

It was great working with you! Nice job!

**Comment by JeffBlodgett** [comment]
I had too, but spent a good chunk of time looking into dynamicly-proxying 
decorators on Thursday which didn't solve my problem.  The solution worked 
(DiscoveredPath class) but isn't recommended.  Oracle docs warn that the 
the construction of concrete Path instances should be reserved by those 
created custom file systems.

Forgot to mentikn earlier that your finding that the Exception between 
JUnits not appearing when run atop a Linux platform makes me believe that 
the proble is with the Oracle JFileChooser even more so.  Comments I have 
read have noted that it is only reproducable atop Windows.
- Jeff

**Pull request merged**
