### PR TITLE
Initial discovery and tests for FileEnumeration package

### PR DESCRIPTION
**Pull request by JeffBlodgett**
Not a request to merge yet... just opening this pull request for further discussions.  We just did a lot of that on Google Hangouts tonight where we decided that the code of the FileDifferentiation package needs to output List<String, List<File>> (input is the Map that is output by FileEnumeration).  This FileEnumeration code needs to be tweaked to permit input of a list of sources rather than just a single source (Path).  Oh, and FileManagement's copyPathname method will need an overload for taking a list of specific files/folders to copy (bypassing it's internal enumeration capability... which should probably be tweaked to use that provided by FileEnumeration package.  Lots to do :-)

### CODE REVIEW

**Comment by JeffBlodgett** [comment]
Per Hangouts discussion, I'm committing to my having the FileEnum and FileDiff stuff finished by weekend's end (evening of July 3rd). Then I can add an overloaded copyPathname method to FileManagement on Monday that takes a list of files/folder names to copy (bypassing its internal file enumeration). Will merge at that point and then I'll have the rest of that week to tweak the internal copy mechanism to get around the 260-char Windows pathname limit and improve the test class for FileManagement (neating up, breaking up of existing tests into more discrete ones, and additional tests in whole).

**Comment by JeffBlodgett** [comment]
Umm... meant so set self-deadline to evening of July 6th (not the 3rd).  Sorry if I confused.  Progress wise, the FileEnumeration package is now able to enumerate a list of given "source" paths for files and folders (recursively or not) as well as a single source path.

**Comment by JeffBlodgett** [comment]
Olga: I'm responding to your E-mail here, having just posted a fresh commit from work done last evening on the FileDiff and FileEnum packages.

This evening will likely be a late one, but I will be posting a commit here (in this pull request for the "DifferentiationEnumerationKickoff" branch) that will contain the proposed final "look" of the public API for the FileEnumeration and FileDifferentiation packages.

Everything you mentioned in your E-mail is spot-on...

(a) FileEnumerator package has a method that takes multiple source files/folders, and that outputs a Map that can feed into a method of FileDifferentiator to identify duplicate files.  It is unlikely I will be getting to the overloaded method in the FileManager that takes the Map outputted from the FileEnumerator package until tomorrow morning.

(b) Total number of files being copied and total number of bytes: the addition of methods to provide this information in the FileEnumeration package is amongst my list of tasks tonight.

(c) Copy operations: see the available methods of the SwingCopyJobListener.  One method is called by the copy job for providing percentage updates for the overall copy operation.  The other provides a percentage update for the current file being copied (or folder being created, which is simply posted at 100% as soon as it is created).  It is up to you to provide implementations for these methods in your own instance of the "SwingCopyJobListener" that is registered with the copy job. 

I'm heading out to a family gathering in a few minutes and will be "back at it" this evening, around 8:00 PM.  Will not be hitting the sack until the public API for the FileDifferentiation and FileEnumeration packages is complete.  Then, tomorrow morning I'll make the final changes to the public API on the FileManagement package.

**Comment by JeffBlodgett** [comment]
Son is sick so decided to remain at home and skip family get-together.  Just implemented (proposed) final changes to the FileEnumeration and FileDifferentiation packages.  Proper documentation is what is left.  Please let me know if this pull request can be merged with master to make these two packages available as-is in master.  I currently have 81% line coverage in FileEnumeration package tests and 86% line coverage in FileDifferentiation package tests.  First item on tomorrow morning's docket is to add the ability to pass the Map output from FileEnumeration to a FileManager.  Once that is done, the public API for the FileManagement package will be complete and I can go back to properly documenting all this and modifying CopyJob internals to support long pathnames atop the Windows platform.

**Comment by programming2web** [comment]
Jeff, thank you very much!!!

I will examine the FileEnumeration and FileDifferentiation packages tomorrow.

I did a stub for CopyScreen for now through javax.swing.Timer in GUI-and-controller branch. It would be wonderful if you could have some time to take a look. I would really appreciate. No rush though. 
The thing that confuses me with UpdateCopyJobProgress method of SwingCopyJobListener interface is that it only provides total percentage while it would also be nice to show total number of files that are already copied and total bytes already copied. But certainly it's not critical and I can easily remove this functions from gui and display only percentage. Currently I implemented it in copyJobListener in gui package (doesn't implement the proposed interface yet) in GUI-and-controller branch. 

Thank you.

**Comment by JeffBlodgett** [comment]
I like what you want to do - please don't change your plans.  There is a 
separate method of the SwingCopyJobListener interface that provides 
percentages of individual files and folders.  As far as the total number of 
files (excluding folders) to be copied/created in the target path, that can 
be be obtained via the FileDiscoverer object's 
getFileCountFromLastEnumeration() method.  There is also a 
getTotalFileByteCountFromLastEnumeration() method.  In practice, you would 
call the FileDiscover object's getPathnames method (the version that takes 
a list of source paths), pull the total file and byte counts using above 
methods, and pass the output of the getPathnames method to copyPathnames 
(or the method of the object that identifies duplicates).  The overload for 
the copyPathnames method of the FileManager that will take the Map output 
by FileDiscoverer will come into existance in the AM.

Does this help?
- Jeff

**Comment by programming2web** [comment]
It helps a lot. Jeff, thank you very much!!!
It's much more clear now.
Please do merge whenever you are ready and I'll replace my copy operation stub with real methods.

**Comment by JeffBlodgett** [comment]
I’m making things clearer now within the FileEnumeration and FileDifferentiation packages before committing some changes and applying a merge.  Amongst these changes is a correction to exception handling in the FileDiscoverer class and the enabling of static factory classes for these packages so a consumer need only need to know about the “FileEnumerator” and “FileDifferentiator” types (similar to how the FileManagement package has a factory class that returns a SwingFileManager object).  Also, I have renamed the previously discussed FileEnumerator method to “getFileCount()” and “getByteCount()”.  The documentation for those methods explains that they return the counts for the most recent enumeration (Path discovery).

Olga: when you go to create a copy job during your implementation, keep a reference to the returned SwingCopyJob object… even though there is only one copy job in this single-threaded background copy and no need to updates from two or more jobs apart, the SwingCopyJob object has a “cancelJob()” method that you could link to a button on the GUI so the user may cancel an on-going copy.

Commit and merge coming as soon as possible for FileEnumeration and FileDifferentiation packages so I may implement a copyPathnames (plural) method for accepting the Map of Path objects coming from a FileEnumerator as input…
- Jeff

**Comment by JeffBlodgett** [comment]
Merging this branch now so I may return my attention to the FileManagement class.

**Comment by JeffBlodgett** [comment]
Olga, Dan: I just merged the fully functional FileEnumeration and FileDifferentiation packages.  See their respective tests – should assist with usage.

I’m working on the FileManagement package again now.  First I’m adding a getPathnames method for inputting the Map of paths returned by a FileEnumerator, after which there will be a requested merge… few hours from now.
- Jeff

**Comment by dbendig** [comment]
Thanks Jeff, great work again. I'll update my Persistence code with this and test it out and then maybe we can merge #11 into main as well.

**Comment by smarks** [comment]
Great to see all this dialog - this comment applies to all the recent reviews not just this one. Seems like some good teamwork is producing good results.

**Pull request merged**
