### PR TITLE
Layout pictures

### PR DESCRIPTION
**Pull request by programming2web**
Created 2 views:
1. Select folders to search for duplicates
2. Duplicate find results view
Apologize for my design skills...
Hope it will help us to further refine our project vision.

### CODE REVIEW

**Comment by programming2web** [comment]
Just finished the first draft of the GUI and pushed it here. 
Took me much longer than I thought. Somehow it turned out that I don't know swing almost at all. So it was great learning experience!

I decided to do 3 screens as the latest commit says:
1. Select Folder
2. Duplicates Results
3. Copying Process
Separating these steps into 3 distinct screens rather than combining them into one window would provide better user experience, because at any step of the process there is really no need to interact with the other 2, so it's better to just remove them from display until the next step occurs. 
The following buttons are currently working on all screens and switch the window to the appropriate screen:
Copy To, Find Duplicate Files, New Search
Please feel free to play with it

Let me know whether you don't mind if I merge this branch into master. 
Thanks!

**Comment by smarks** [comment]
Hi, I see this was merged, but I don't see any additional discussion about it. Was that discussion taking place somewhere else (like in email) ? If so I'd like to see it here. It not, I'd like to see it here too :>

**Comment by JeffBlodgett** [comment]
Sorry professor - we have been discussing on Hangouts and need to do more of that here to ensure you are kept up to date.  These merged changes were ok'ed by the group.  They include Olga's draft GUI forms and a state-of-the-project document for Dan and I to fill in for Monday.  I'll be pushing, commenting, and merging my current FileManagement branch later in the day tomorrow.  Main reason why I'm hot to trot on the merge is for the cobertura support I have wired into build.xml.  With it, the team will be able to run test coverage reports.

**Comment by programming2web** [comment]
Sorry about that. We've been discussing the GUI in this branch on chat and didn't put much comments in here. Next time will do better.

**Comment by smarks** [comment]
Not a problem. Good to get a chance to clarify the protocol.

Thanks, Spencer

On Fri, Jun 20, 2014 at 6:01 AM, Olga notifications@github.com wrote:

> Sorry about that. We've been discussing the GUI in this branch on chat and
> didn't put much comments in here. Next time will do better.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JeffBlodgett/FileSieve/pull/2#issuecomment-46663084.

## 

Spencer Marks
http://smarksphotography.com

**Pull request merged**
