### PR TITLE
JavaDoc editing and additions

### PR DESCRIPTION
**Pull request by JeffBlodgett**
Please give the green light for this merge and I'll make it so. This is my last commit. I was going to continue working on the JavaDoc this evening and instead spent the whole night trying to determine why IDEA went belly up on me when I shut down this afternoon. I have rebuild the IDEA project files and gotten most everything compiling/running from within IDEA again but I'm still having trouble with JUnit.  Everything compiles, tests, and runs fine from a command line with ANT though.

### CODE REVIEW

**Comment by JeffBlodgett** [comment]
Bother... IDEA simply won't recognize JUnit nor JSoup now.  Guess I'm all done.  Will wait a few days tear everything apart again to try to determine where it went wrong.  Will probably delete everything IDEA related, uninstall completely, and re-install.

**Comment by smarks** [comment]
That seems extreme. Let me know if I can help.

S.

**Comment by dbendig** [comment]
This looks fine and runs well on my machine, Jeff. Please merge.

Also, I've tried to recreate the error message you're getting during the tests to no avail. Since we're at the end and that is a minor bug, I think we should turn it in.

As for IDEA... I had these problems at one point as well, after we renamed the project. What I found was that when I checked the project back out IDEA didn't properly add the library references. I had to go to Project Structure / Libraries / lib / and then add the libraries we're using manually so that IDEA would recognize them. Meanwhile I could compile the project with ant just fine.

**Comment by smarks** [comment]
Right, it just has to work with Ant.

Spencer

**Comment by JeffBlodgett** [comment]
Thanks Olga, but my problems with IDEA aren't just a library or missing JAR issue.  Initially IDEA wasn't even able to find any class in any of our packages.  I had to rename classes and then return them to their original names to get IDEA to "find" them.  Very odd.  I'll play with it some tonight.  It might have had something to do with the two or three IDEA updates received over the last couple of days.  I think they may have botched one (the first did indeed generate errors) and were then pushing out updates to try to correct.  As an IT guy, I should know better than to blindly hit the upgrade button! All of this is why I'm going to try starting with IDEA completely removed, re-install it, plus import the project anew.

This is all academic... I'm finished with the project (last night's commit was my last).  Always room for a lot of improvement but I've eaten up my quota of family time for the week :-)

Great job everyone!

**Comment by JeffBlodgett** [comment]
Got IDEA working again... it took a complete uninstall/reinstall.  After importing and configuring our project for IDEA I am once again able to compile and run (tests and the project itself).

**Pull request merged**
