### PR TITLE
Working on Controller

### PR DESCRIPTION
**Pull request by programming2web**
Added Controller class, anonymous action listeners for buttons, JTree with FileTreeModel for SelectScreen and app main class - FileSieve.java (still need to add it to build.xml though).
Also included Mockito in lib as I'm using it in tests.
It took me much longer than it should have to decide on the structure of the whole thing. And it probably is still not the best one. But at least now I got moving on GUI. If you have any advise on how to improve it I would greatly appreciate it. 
Thanks!

### CODE REVIEW

**Comment by programming2web** [comment]
The last commit has a stub implementation for the copy Screen and first attempt for copyJobListener (doesn't implement the suggested interface yet). The "testfiles" folder is for feeding the stub with files and will be deleted eventually.
Will keep working on results screen and integration with persistence classes.

**Comment by programming2web** [comment]
All screens are now complete and connected to BusinessLogic methods. Stubs were replaced with real methods. Everything seems to be working nicely so far. 
According to Cobertura report the test coverage for gui classes is about 90%. Would really appreciate if you could let me know whether I can merge. Would like to do it tomorrow am if you don't mind.
Next week will work on connecting Persistence classes, improving the tests and documentation. Also will need to modify build.xml to include the run target. 
Thanks!

**Comment by dbendig** [comment]
Great work. I checked over everything and I don't see any reason not to merge.

**Comment by programming2web** [comment]
Thanks, Dan. Finally merging this long-lasting branch! Hooray!

**Comment by JeffBlodgett** [comment]
Thanks team!  I can't wait to pull master during chat tomorrow evening and 
take a look!  I found a corner of the camp ground that has some 
semi-reliable 4G service.  The wi-fi service here is unusable.
- Jeff

**Pull request merged**
