### PR TITLE
Refactoring of FileManagement branch with addition of a copyPathnames method

### PR DESCRIPTION
**Pull request by JeffBlodgett**
Not a request to merge just yet (I have tests to edit and write to confirm proper functionality) but I'm starting this pull request now, following a fresh push of my changes to this package moments earlier, to show that the FileManagement package is now able to accept a Set<Path> with one or more folder/file sources to be copied.  The Map<Path, BasicFileAttributes> returned by a FileEnumerator can be passed to the SwingFileManager's copyPathnames method by passing MapInstance.keySet().

### CODE REVIEW

**Comment by JeffBlodgett** [comment]
Working on "SwingWorkerBasedFileManagerTest" class now... new tests are needed to confirm new functionality, to increase test coverage, and I am breaking up old tests into more discrete pieces.  I never addressed first round code review comments within this class so those corrections are now being factoring in.

**Comment by JeffBlodgett** [comment]
Now would be a good time to merge these changes to the FileManagement package.  SwingFileManager instances now have a copyPathnames (plural) method available.  Please let me know if I merge it so I can proceed with internal modifications to the SwingCopyJob class to enable support for copying of/to long pathnames atop the Windows platform.

**Comment by programming2web** [comment]
Jeff, please do merge. It would help me a lot with GUI building. 
Thank you!

**Comment by JeffBlodgett** [comment]
Just merged this latest changes to FileManagement package.  Going to start the day tomorrow with one more test for this package and determining why the SwingCopyWorker's awaitCompletion() method isn't throwing internally thrown exceptions from the class' background thread while moving on to support for long pathnames.

**Comment by JeffBlodgett** [comment]
Corrected problem with SwingCopyWorker class' "awaitCompletion()" method not re-throwing exception that occur on the background thread.  You wouldn't use this method in the GUI code, where the goal is to remain responsive, but its important in the test class where it is used to wait for these otherwise concurrent jobs to complete and to detect internal exceptions. Continuing with writing of another test now, followed by advancement to long pathnames.

**Comment by JeffBlodgett** [comment]
In this latest test, I found some issue with FileManagement as it currently exists.  Working to resolve them... then there will be another pull request.  The test simulates the output that would come from a FileEnumerator (calling the copyPathnames() method and providing a Set of paths to copy, with recursion disabled since the FileEnumerator did all the work of acquiring the exact paths of the files and folders to copy).

**Pull request merged**
