### PR TITLE
File management

### PR DESCRIPTION
**Pull request by JeffBlodgett**
Interim corrections to FileManagement package in advance of changes to have copyPathname method return an instance of a new class named "CopyJobRelay".  This class will incorporate and render the custom PropertyChangeLister class at the bottom of the ConcurrentFileManagerTest file obsolete.

### CODE REVIEW

**Comment by JeffBlodgett** [comment]
There were/are problems with the build.xml file from a cobertura perspective... I had it configuring instrumentation twice and then it wasn't set to use the instrumentation framework correctly in the test target.  Resolve that now...

**Comment by JeffBlodgett** [comment]
Yeah... it might have seemed as though the Cobertura framework was properly integrated but there were numerous problems in the build.xml file.  I'll push an updated copy via this branch tonight.

**Comment by JeffBlodgett** [comment]
I think it was working but there at least 3 big errors in build.xml.  
Please appologize to prefessor - I won't be able to make it to tonight's 
session.  My wife hit a deer on her way home and I'm picking her up now.  
Probably going to have her checked out at ER.  More later... please let me 
in a nut shell how the session went when over.
- Jeff

**Comment by JeffBlodgett** [comment]
Lots to say in this update. First, changes have been made to build.xml as suggested by professor during Monday's (awsome!) code review.

This week I got the FileManagement package nailed down to where I am much happier with its implementation.  What I had put together come the start of the week was an overly complicated mess consisting of a ConcurrentFileManager that had a private extended a SwingWorker class for handling background copies and whose copyPathname method passed a reference to a constructed worker to a "special" object that received events from the worker, interrpreted them, and forwarded them, using a PropertyChangeSupport object defined in an inherited class of the FileManager, to a PropertyChangeListener registered with the inherited class for receiving events from any numer of copy jobs...  geese!  It worked but was very messy.  Had to pass lots of references around and fire/interpret events left and right.  I hacked it down to the following:

We now have a relatively simple concrete FileManager with a brief "copyPathname" method returning an instance of a new class named "CopyJob".  The method calls a static factory method  of the CopyJob class,  which caches a list of ongoing copy jobs and returns a reference to an ongoing job if "equal" to the one being requested, registering the specified CopyJobListener as an additional listener for that in-progress job.  If the requested job is dissimilar to ongoing jobs and isn't specifiying a destination path that overlaps with that of an ongoing job then a new CopyJob is created.  The CopyJob class itself encapsulates the private inner class that is the extended SwingWorker (makes more sense this way) and that worker instance notifies CopyJobListener instances (CopyJobListener is a new interface) directly - there is no longer any use of the PropertyChangeSupport framework.

The FileManagement package now consists of the following. Internally it is highly extensible. Externally, the API is minimal:

package-private interface "FileOpener"
package-private interface "FileDeleter"
package-private interface "FileCopier"
public interface "SwingFileWorker", which defines a type to be retuned by the package's FileManagerFactory class:
    interface SwingFileManager extends FileOpener, FileDeleter, FileCopier<CopyJob, CopyJobListener>
public class "CopyJob"
public interface "CopyJobListener"
package-private abstract class "AbstractFileManager"
package-private concrete class "SwingWorkerBasedFileManager" (extends "AbstractFileManager" and implements "SwingFileWorker")
public static factory class "FileManagerFactory" for acquiring FileManager instances

In practice:

SwingFileManager swingFileManager = FileManagerFactory.getSwingFileManager();
swingFileManager.setCopyOperationsListener(this);
CopyJob myCopyJob = swingFileManager.copyPathname(fileToCopy, anotherFolder, true, false);

On 2nd line of example, "this" implements interface "CopyJobListener".
Each method of the CopyJobListener interface passes a reference to the particular CopyJob instance from which the progress update is coming, so a CopyJobListener registered with multiple copy jobs can differentiate/filter them by CopyJob reference.

Still need to come back to FileManagement to make it able to create Windows pathnames exceeding 260 charactors but I first I need to fill in the FileEnumeration and FileDifferentiation packages.  There will be at least one more push for the FileManagement branch tonight as I document and neaten things up.

**Comment by JeffBlodgett** [comment]
There's a minor logic error in the CopyJob class' factory method but I'm just going to mark as it as "todo" and move on for now.  Additional documention will come as times allows - it will get done, as will improvements to the testCopyPathname method, which needs to be broken up separate tests per code review.  For now, I'd like to merge what there is of the FileManagement class into master tonight, after the kids are in bed.

I think it's most important for me to get the FileEnumeration class on its feet now whereas Olga will need it fill the control she is preparing for displaying and selecting files/folders to copy.  That class will also provide a means of calculating the total number of bytes to be copied.  Do all agree?

**Comment by programming2web** [comment]
Exceptional work, Jeff! 
Thanks a lot for writing CopyJobListener interface and giving usage instructions for it. It helps a lot and makes much more sense to me now. 
Regarding the File Enumeration - for the filepaths selection screen (first screen of the app) I use FileTreeModel for a JTree. I found the code online and wrote tests for it. It might not be the best solution but at least it works for now. I'm going to post it tonight to a separate branch.
No objections against merging this branch into master.  
Thank you for all the hard work!

**Comment by JeffBlodgett** [comment]
Thanks Olga - I'm getting into the code a little now (kids are sleeping).  Before I push a small update later this evening I think I'm going to rename the "CopyJob" class and "CopyJobListener" interface to "SwingCopyJob" and "SwingCopyJobListener".  This aligns these types with the naming of the "SwingFileManager" returned by the "FileManagerFactory" class' factory method.  That will be the last signification change to the FileManagement package's API (I hope) since changes affect the code of our other packages.

In this naming scheme, I'm loosely using the prefix "Swing" as an indication to ourselves that long-running operations are executed on SwingWorker background threads (if this fact is a little too implementation specific, it isn't spelled out in the API's  javadocs).

**Comment by programming2web** [comment]
Sounds good to me.

**Pull request merged**
